---
abstract: 'RT Authen-ExternalAuth Extension'
author:
  - 'Mike Peachey <zordrak@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: 'GPL version 2'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-ExternalAuth
no_index:
  directory:
    - etc
    - html
    - inc
recommends:
  CGI::Cookies: 0
  DBI: 0
  Net::LDAP: 0
  Net::SSLeay: 0
version: 0.08
